name: Docker Image CI

on:
  workflow_run:
    workflows: ["Laravel"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Log in to GitHub Container Registry
    #   run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    # - name: Set repository name to lowercase
    #   id: repo-name
    #   run: echo "repo_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ghcr.io/${{ env.repo_name }}/my-image-name:latest

    # - name: Push the Docker image
    #   run: docker push ghcr.io/${{ env.repo_name }}/my-image-name:latest
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
